/**
 * RC2.3.9 — canonical beta suites: the single definition of what `validate:beta` runs.
 *
 * Every step of the frozen legacy chain (docs/release/validate-beta-legacy.json) appears in
 * exactly one suite, in its original relative order (or is retired with recorded
 * equivalence in docs/release/gate-retirements.json). Suites are independent: CI runs each
 * as its own job on a fresh checkout. Additions beyond the legacy chain are marked `added`.
 * Edited by hand when a gate is added — the convergence gate fails on any drift.
 */
export const SUITES = [
  {
    id: "release-truth",
    domain: "release",
    description: "Fast failure first: convergence + product truth, typecheck, secrets/security boundaries, freezes, fingerprint chain, release evidence.",
    steps: [
      "gate:rc2-3-9-stack-convergence",
      "validate:public-beta-feature-freeze",
      "validate:rc-learning-loop-freeze",
      "validate:operational-evidence",
      "test:operational-evidence",
      "validate:release-evidence-freshness",
      "test:release-evidence-freshness",
      "validate:rc1-2-freeze",
      "validate:rc13-curriculum-freeze",
      "validate:feature-truth",
      "test:feature-truth",
      "validate:product-claims",
      "test:product-claims",
      "validate:ghost-features",
      "test:ghost-features",
      "validate:rc15-freeze",
      "typecheck",
      "validate:node-runtime",
      "validate:structure-index",
      "validate:encoding",
      "validate:v410a1-freeze",
      "validate:app-environment",
      "validate:privacy-consent",
      "validate:client-diagnostics",
      "test:stale-bundle",
      "validate:security-boundaries",
      "validate:social-profile-security",
      "validate:seo",
      "validate:production-no-fixtures",
      "validate:rc2-content-freeze",
      "test:rc2-content-freeze",
      "validate:rc2-candidate-config",
      "test:rc2-candidate-config",
      "validate:rc2-candidate-drift",
      "test:rc2-candidate-drift",
      "validate:rc2-candidate-infra",
      "test:rc2-candidate-infra",
      "validate:release-candidate",
      "test:fingerprint-chain",
    ],
  },
  {
    id: "learner-systems",
    domain: "media-speech-hanzi-mastery",
    description: "RC2.2.32/RC2.3.4–2.3.8 learner systems: canonical voice, speech, Hànzì, Personal Mastery, sensory/guidance, identity; SRS/tone trainer.",
    steps: [
      "validate:guide-dialogue-contract",
      "test:guide-dialogue",
      "validate:guide-dialogue-motion",
      "test:guide-dialogue-motion",
      "validate:guide-text-voice",
      "test:guide-text-voice",
      "validate:journey-guide-explanations",
      "test:journey-guide-explanations",
      "validate:hanzi-memory-integration",
      "test:hanzi-memory-integration",
      "validate:tone-integration",
      "test:tone-integration",
      "validate:feedback-audio",
      "test:feedback-audio",
      "validate:learning-event-semantics",
      "test:learning-event-semantics",
      "validate:speech-attempt-integrity",
      "test:speech-attempt-integrity",
      "validate:mission-speech-integrity",
      "test:mission-speech-integrity",
      "validate:hanzi-builder-coverage",
      "test:hanzi-builder-integrity",
      "validate:tone-trainer",
      "test:srs-steps",
      "test:speech",
      "test:mandarin-speech-text",
      "gate:rc2-3-4-hanzi-writing",
      "test:free-tier-guardrails",
      "gate:rc2-3-5-speech",
      "gate:rc2-3-6-personal-mastery",
      "gate:rc2-3-7-sensory-guidance",
      "gate:rc2-3-8-auth-identity",
      "validate:human-qa-prebeta",
      "test:human-qa-prebeta",
      "validate:public-beta-trust",
      "test:public-beta-trust",
      "gate:rc2-2-32",
    ],
  },
  {
    id: "pedagogy-v6-stack",
    domain: "pedagogy",
    description: "RC2.3.0–2.3.3 wave gates: Pedagogy V6, Visual First, Human Everyday, Culture Deep.",
    steps: [
      "gate:rc2-3-0-pedagogy-v6",
      "gate:rc2-3-1-visual-first",
      "gate:rc2-3-2-human-everyday",
      "gate:rc2-3-3-culture-deep",
    ],
  },
  {
    id: "pedagogy-structure",
    domain: "pedagogy",
    description: "Curriculum structure, locale parity (EN/PT topics), lessons, generated-task integrity and regressions.",
    steps: [
      "validate:visual-asset-transparency",
      "validate:visual-association-integrity",
      "test:visual-association-integrity",
      "validate:tone-contrast-progression",
      "test:tone-contrast-progression",
      "validate:tone-contrast-no-new-vocab",
      "validate:i18n",
      "test:i18n",
      "validate:first-20-en",
      "test:first-20-locale-parity",
      "validate:journey-en",
      "test:topics-21-50-locale-parity",
      "test:topics-51-80-locale-parity",
      "test:topics-81-113-locale-parity",
      "test:stable-pedagogy-ids",
      "validate:en-core-surfaces",
      "validate:pinyin-display",
      "validate:lessons",
      "validate:pedagogy-wave-one",
      "test:mastery-loop",
      "test:topic-mastery-path",
      "test:lab-mastery-pass4",
      "validate:generated-task-integrity",
      "test:generated-task-integrity",
      "validate:mastery-planner-integrity",
      "test:generated-task-regressions",
    ],
  },
  {
    id: "pedagogy-mastery",
    domain: "pedagogy",
    description: "Mastery depth/coverage/quality, review, media, capsules, foundations, first contacts, tone, answer fairness, module skip.",
    steps: [
      "validate:generated-answer-ref-consistency",
      "validate:generated-explanation-integrity",
      "validate:generated-help-integrity",
      "validate:generated-audio-integrity",
      "validate:generated-option-integrity",
      "validate:generated-semantic-diff",
      "validate:rc14-curriculum-topology",
      "validate:rc14-no-vocab-growth",
      "test:generated-task-objective",
      "validate:topic-mastery-depth",
      "validate:topic-fidelity",
      "validate:exercise-feasibility",
      "test:exercise-feasibility",
      "test:pinyin-topic-fidelity",
      "test:china-real",
      "test:mastery-v32",
      "test:mastery-coverage",
      "test:mastery-coverage:strict",
      "test:mastery-quality",
      "test:mastery-quality:all",
      "validate:mastery-network-growth",
      "validate:review-mastery",
      "validate:transfer-review",
      "validate:lesson-options",
      "test:pedagogy-runtime-qa",
      "validate:corpus",
      "validate:atlas",
      "test:immediate-remediation",
      "validate:review-content-integrity",
      "test:placement-v2",
      "test:placement-locale-parity",
      "validate:teach-before-test",
      "validate:journey-readiness",
      "validate:lesson-media",
      "test:media-progress",
      "test:media-resume",
      "test:media-fallback",
      "test:capsule-locale-variants",
      "test:media-telemetry-privacy",
      "validate:capsule-pedagogy-handoff",
      "validate:lesson-catalog",
      "validate:core-instruction-slots",
      "validate:foundation-capsules",
      "validate:capsule-presentation-parity",
      "validate:foundation-locale-parity",
      "validate:first20-instruction-order",
      "validate:foundation-packs",
      "test:learner-response",
      "test:v490-orchestration",
      "validate:tone-teach-before-test",
      "validate:tone-transfer-coverage",
      "validate:tone-transfer-honesty",
      "test:tone-transfer",
      "test:tone-learning-ladder",
      "validate:answer-position-fairness",
      "test:placement-option-permutation",
      "validate:journey-option-position",
      "test:v491-boosters",
      "validate:teach-before-test:journey",
      "validate:streak-recovery",
      "validate:module-skip-access",
      "validate:module-review-coverage",
    ],
  },
  {
    id: "pedagogy-progression",
    domain: "pedagogy",
    description: "Modality/listening/image contracts, conversation pedagogy, lexical growth, transfer and prerequisite progression, early communicative win, capability closure. Owns every report generator checked by validate:report-freshness, which runs last here (it must follow the generators).",
    steps: [
      "validate:image-exercises",
      "validate:listening-affordance",
      "validate:modality-contract",
      "validate:compare-with-image",
      "validate:visual-consistency",
      "validate:visual-assets",
      "validate:tone-progression",
      "validate:conversation-scenes",
      "validate:conversation-vocabulary",
      "validate:conversation-vocabulary-srs",
      "validate:conversation-loop",
      "validate:conversation-pedagogy",
      "validate:conversation-migration",
      "npm run validate:exercise-depth -- --beta",
      "validate:lesson-novelty",
      "validate:perception-drills",
      "validate:lexical-progression",
      "validate:atlas-utilization",
      "validate:lexical-growth",
      "validate:seed-decay",
      "validate:lexical-registry",
      "validate:vocabulary-packets",
      "validate:productive-vocabulary",
      "validate:productive-core",
      "validate:first-50-audit",
      "validate:journey-51-100-roadmap",
      "validate:atlas-roadmap",
      "validate:lexical-aging",
      "validate:word-layer",
      "validate:production-transfer",
      "test:cognitive-budget",
      "validate:transfer-integrity",
      "validate:transfer-prerequisites",
      "validate:structural-concepts",
      "validate:prerequisite-progression",
      "test:transfer-scaffold",
      "test:early-transfer",
      "test:early-transfer-negative",
      "validate:error-diagnosis",
      "validate:onboarding-pace",
      "test:pedagogical-cjk",
      "validate:first-communicative-win",
      "validate:acquisition-momentum",
      "validate:early-transfer-ladder",
      "validate:report-freshness",
      "test:first-20-sessions-pack",
      "gate:rc2-2-8-learning-gamification",
      "gate:rc2-2-9-capability-closure",
      "gate:rc2-2-11-experience-coherence",
    ],
  },
  {
    id: "conversation-everyday",
    domain: "pedagogy",
    description: "China survival scenarios, conversation coherence/naturalness, capstones, production scaffolding, first contacts.",
    steps: [
      "validate:china-survival-restaurant",
      "test:china-survival-restaurant",
      "validate:conversation-decisions",
      "test:conversation-decisions",
      "validate:china-survival-shopping",
      "test:china-survival-shopping",
      "validate:china-survival-mobility",
      "test:china-survival-mobility",
      "validate:china-survival-hotel",
      "test:china-survival-hotel",
      "validate:china-survival-airport",
      "test:china-survival-airport",
      "validate:china-survival-health",
      "test:china-survival-health",
      "validate:china-survival-emergency",
      "test:china-survival-emergency",
      "validate:health-conversation-naturalness",
      "test:health-conversation-naturalness",
      "validate:china-survival-everyday",
      "test:china-survival-everyday",
      "validate:china-survival-capstone",
      "test:china-survival-capstone",
      "validate:capstone-no-new-vocabulary",
      "test:capstone-no-new-vocabulary",
      "validate:capstone-transfer",
      "test:capstone-transfer",
      "validate:travel-conversation-naturalness",
      "test:travel-conversation-naturalness",
      "validate:conversation-lexical-bridge",
      "test:conversation-lexical-bridge",
      "validate:production-scaffolding",
      "test:production-scaffolding",
      "validate:hanzi-fill-integration",
      "test:hanzi-fill-integration",
      "validate:conversation-auto-reveal",
      "test:conversation-auto-reveal",
      "validate:identity-people",
      "test:identity-people",
      "validate:routine-time",
      "test:routine-time",
      "validate:conversation-coherence",
      "test:conversation-coherence",
      "validate:first-contacts-theme",
      "validate:first-contacts-teach-before-test",
      "validate:first-contacts-conversation-readiness",
      "validate:first-contacts-checkpoint",
      "validate:first-contacts-locale-parity",
      "validate:conversation-lexical-growth",
      "test:vocabulary-packet-conversation",
      "validate:conversation-capabilities",
      "validate:china-survival",
    ],
  },
  {
    id: "culture",
    domain: "culture",
    description: "Culture content truth, history, festivals, missions, Journey integration, playability.",
    steps: [
      "validate:culture-content",
      "test:culture-content",
      "validate:culture-collections",
      "test:culture-collections",
      "validate:culture-source-coverage",
      "test:culture-source-coverage",
      "validate:culture-festival-date-policy",
      "test:culture-festival-date-policy",
      "validate:culture-truth-classification",
      "test:culture-truth-classification",
      "validate:culture-legend-vs-history",
      "test:culture-legend-vs-history",
      "validate:culture-no-lexical-pollution",
      "test:culture-no-lexical-pollution",
      "validate:culture-hub-collections",
      "test:culture-hub-collections",
      "validate:culture-history-integrity",
      "test:culture-history-integrity",
      "validate:culture-history-chronology",
      "test:culture-history-chronology",
      "validate:culture-distribution",
      "test:culture-distribution",
      "validate:culture-missions",
      "test:culture-missions",
      "validate:culture-memory",
      "test:culture-memory",
      "validate:culture-gamification",
      "test:culture-gamification",
      "validate:culture-teach-before-test",
      "test:culture-teach-before-test",
      "validate:culture-explanation-depth",
      "test:culture-explanation-depth",
      "validate:culture-journey-integration",
      "test:culture-journey-integration",
      "validate:culture-native-lessons",
      "test:culture-native-lessons",
      "validate:culture-journey-nodes",
      "test:culture-journey-nodes",
      "validate:culture-progression-gates",
      "test:culture-progression-gates",
      "validate:journey-culture-moments",
      "test:journey-culture-moments",
      "validate:culture-standard-tasks",
      "test:culture-standard-tasks",
      "validate:culture-playability",
      "test:culture-playability",
      "validate:culture-story-audio",
      "test:culture-story-audio",
      "validate:culture-rewards",
      "test:culture-rewards",
      "validate:culture-journey-placement",
      "test:culture-journey-placement",
      "validate:navigation-history-integrity",
      "test:navigation-history-integrity",
    ],
  },
  {
    id: "experience",
    domain: "experience",
    description: "Lesson/review UX, completion and victory, navigation, mobile/PWA beta readiness.",
    steps: [
      "validate:mobile-beta-readiness",
      "test:mobile-beta-readiness",
      "validate:pwa-release-readiness",
      "test:pwa-upgrade-preflight",
      "validate:public-beta-core",
      "test:public-beta-core",
      "validate:exercise-affordance",
      "validate:lesson-ui-consistency",
      "test:lesson-ui-consistency",
      "validate:completion-experience",
      "test:completion-experience",
      "validate:review-advance",
      "test:review-advance",
      "validate:task-modality-coherence",
      "test:task-modality-coherence",
      "validate:adaptive-plus-round",
      "test:adaptive-plus-round",
      "validate:adaptive-remediation-diversity",
      "test:adaptive-remediation-diversity",
      "validate:victory-minimalism",
      "test:victory-minimalism",
      "validate:review-finite-session",
      "test:review-finite-session",
      "validate:review-task-parity",
      "test:review-task-parity",
      "validate:review-answer-integrity",
      "test:review-answer-integrity",
      "validate:review-help-parity",
      "test:review-help-parity",
      "validate:completion-layout",
      "validate:lesson-recovery",
      "test:review-ux",
      "test:assembly-ux",
      "test:piece-bank-shuffle",
      "test:body-scroll-lock",
      "test:session-plan-lock",
      "test:progress-loading",
      "test:player-ux",
      "validate:exercise-theme-tokens",
      "test:media-completion",
      "validate:glossary-ui",
      "validate:lesson-victory-ui",
    ],
  },
  {
    id: "identity-commercial",
    domain: "identity",
    description: "Account/auth/cloud-first, sync, entitlements, commercial/family/business, economy, backend contracts, leagues.",
    steps: [
      "validate:live-league",
      "test:live-league",
      "test:cloud-first-auth",
      "test:onboarding-handoff",
      "test:create-account-locale-contract",
      "test:brazil-beta-readiness",
      "test:staging-activation",
      "test:v476-live-validation",
      "test:backend-contract",
      "test:mastery-monotonic-contract",
      "test:v478-hosted-gate",
      "test:v489-production-preflight",
      "test:ops-correlation-crypto",
      "test:longyu-only-backend",
      "test:qa-regression-guard",
      "validate:progress-snapshot",
      "validate:sync-merge",
      "test:leagues",
      "test:subscribe-auth-redirect",
      "validate:plans",
      "validate:commercial-pricing",
      "test:commercial-pricing",
      "validate:family-plan",
      "test:family-plan",
      "validate:effective-entitlement",
      "test:effective-entitlement",
      "validate:business-schema-reuse",
      "test:business-schema-reuse",
      "validate:business-seat-reservation",
      "test:business-seat-reservation",
      "validate:business-seat-concurrency",
      "test:business-seat-concurrency",
      "validate:business-overview-rpc",
      "test:business-overview-rpc",
      "validate:business-progress-privacy",
      "test:business-progress-privacy",
      "validate:family-experience",
      "test:family-experience",
      "validate:commercial-product-truth",
      "test:commercial-product-truth",
      "validate:economy",
      "validate:economy-server",
      "test:economy-server",
      "validate:backend-ready",
      "test:entitlements",
      "test:referrals",
      "test:create-account-hardening",
      "test:qa-fast-path",
      "test:rc-hardening",
      "validate:pedagogy-rpc-hardening",
    ],
  },
  {
    id: "android-foundation",
    domain: "android",
    description: "Android native foundation, delivery pipeline and RC2.2.12–RC2.2.2x Android/mobile wave gates.",
    steps: [
      "gate:android-native-foundation",
      "gate:main-delivery-pipeline",
      "gate:rc2-2-12-android-release-readiness",
      "gate:rc2-2-13-native-mobile-experience",
      "gate:rc2-2-14-mobile-learning-polish",
      "gate:rc2-2-14b-locale-course-direction",
      "gate:rc2-2-16-play-internal-beta",
      "gate:rc2-2-17-guided-learning-reliability",
      "gate:rc2-2-17b-guided-journey-parity",
      "gate:rc2-2-18-progressive-discovery",
      "gate:rc2-2-19-guided-simple-verified",
      "gate:rc2-2-20-physical-beta-readiness",
      "gate:rc2-2-21-mobile-native-stability",
      "gate:rc2-2-22-closed-beta-candidate",
      "gate:rc2-2-23-product-convergence",
      "gate:rc2-2-24-android-learning-parity",
      "gate:rc2-2-25-product-experience-closure",
    ],
  },
  {
    id: "android-runtime",
    domain: "android",
    description: "RC2.2.2x–RC2.2.31D Android runtime, deterministic audio and APK runtime proof wave gates.",
    steps: [
      "gate:rc2-2-26-android-physical-closure",
      "gate:rc2-2-27-android-tts-root-cause",
      "gate:rc2-2-28-deterministic-audio",
      "gate:rc2-2-29-launch-convergence",
      "gate:rc2-2-30-closed-beta-entry",
      "gate:rc2-2-31-android-runtime-closure",
      "gate:rc2-2-31b-android-runtime-final",
      "gate:rc2-2-31c-android-runtime-root-cause",
      "gate:rc2-2-31d-apk-runtime-proof",
    ],
  },
];

/** Steps that run in canonical suites but were NOT in the legacy chain (coverage added by RC2.3.9). */
export const ADDED_STEPS = Object.freeze({
  "gate:rc2-3-9-stack-convergence": "RC2.3.9 — new convergence/product-truth gate.",
  "gate:rc2-2-32": "RC2.2.32 voice/speech/guidance gate existed but no workflow or chain ran it.",
  "gate:rc2-3-0-pedagogy-v6": "Previously only in the separate ci.yml rc2-3-stack-gates job; now a canonical suite.",
  "gate:rc2-3-1-visual-first": "Previously only in the separate ci.yml rc2-3-stack-gates job; now a canonical suite.",
  "gate:rc2-3-2-human-everyday": "Previously only in the separate ci.yml rc2-3-stack-gates job; now a canonical suite.",
  "gate:rc2-3-3-culture-deep": "Previously only in the separate ci.yml rc2-3-stack-gates job; now a canonical suite.",
});
